import EditDropDown from "@/components/EditDropDown";
import { Button } from "@/components/ui/button";
import { Download, DownloadIcon, Edit2Icon, Share, Share2Icon, ShareIcon } from "lucide-react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Resume",
  description: "Generated by create next app",
};

export default function BuildLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <div className="h-full w-full flex">
    <div className="w-1/4 max-w-72   bg-[cadetblue]/10 flex flex-col justify-start py-4 gap-3  px-6 max-md:hidden" >
      {/* <Button variant={'outline'} className="py-5" > <Edit2Icon /> Edit</Button> */}
      <EditDropDown />
      <Button variant={'outline'} className="py-5" > <Download /> Download</Button>
      <Button variant={'outline'} className="py-5" > <Share2Icon /> Share</Button>
    </div>
    
    <div className="flex-1">
  {children}
  </div>
  </div>);
}
